### ISSUE TITLE
[BUG] Extension breaks on page load

### ISSUE THREAD

**Issue by BJack0** [V1P3R-FMG/free-map-genie#28]
**Describe the bug**
When loading any map, the page will refresh a couple of times and eventually will load the page. After the map has loaded there are duplicate versions behind the currently loaded map and most functionality breaks.

Unsure how reproducible this bug is, feel free to ask for logs or screenshots.

**To Reproduce**
1. Go to any map on https://mapgenie.io/
2. Wait for the page to refresh two or three times
3. Issue starts

**Screenshots**
https://imagizer.imageshack.com/img922/6708/Aw4DMV.gif

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.61.109

**Comment by MrFusiion** [comment]
Probably the same issue as #21.
Can you check if the extension has enough the needed permissions?.

**Comment by BJack0** [comment]
I check the issue you mentioned and I checked the permissions. The permissions are the same as a fresh install of the plugin, after allowing ALL permissions to the plugin the same issue appears.

![image](https://github.com/V1P3R-FMG/free-map-genie/assets/64874028/c169031d-83fe-4b0a-b089-23c4aa0c09bb)

I looked in the dev tools and found the error above.

![image](https://github.com/V1P3R-FMG/free-map-genie/assets/64874028/6dde8900-399f-4e61-9f8e-1e091723fe7a)

I also found this error related to a font.

**Comment by MrFusiion** [comment]
Well I tried the extension on brave an couple of hours ago and wasn't able to reproduce the error.
But tried it again just now and got the same error/bug.

Apparently `declarative net request` are a bit buggy on Brave?
https://community.brave.com/t/declarativenetrequest-rules/522661
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/998c7502-f8a0-49ba-80a4-502ab66d79b9)

So like to OP said reloading the extension solves the `declarative net request` issue.
And is probably also the reason I got the error only after reopping the browser.

**Comment by BJack0** [comment]
Reloaded the plugin and the issue is resolved.

Maybe as a QOL improvement, would it be possible to add a quick toggle or refresh button similar to U-Block origin?

If brave haven't fixed it in months then who knows when it might get fixed. It will suck having to open the extensions and manually reload it every time. (I don't mind doing so and might even use chrome for my maps while its broken)

Thanks anyway for the fast response
