### ISSUE TITLE
[BUG] Premium Map images not loading

### ISSUE THREAD

**Issue by 1ragnex** [V1P3R-FMG/free-map-genie#38]
hello premium map images not loading on escape from tarkov. 

as you can see, free map works without any problems

![Screenshot 2024-01-23 025238](https://github.com/V1P3R-FMG/free-map-genie/assets/155485714/c8297b98-743b-4c6e-bd06-04a76ff13d80)

however on premium maps (reserve, lighthouse, ground zero etc.) all tags are showing but maps are not loading

![Screenshot 2024-01-23 022410](https://github.com/V1P3R-FMG/free-map-genie/assets/155485714/ead8fe96-1720-45a6-9347-ba0f29970876)

I tried in two different browsers but the result is the same

**Comment by cyb3r1911** [comment]
I have the same, tried to open the premium maps on firefox, brace and chrome and they didnt work anywhere.

**Comment by MrFusiion** [comment]
Looks like they changed the way images are fetched, I will take a look.

**Comment by MrFusiion** [comment]
Should be fixed download the latest release.
