### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by linfazlullin** [V1P3R-FMG/free-map-genie#6]
Hello. Does this extension give access to maps in early access that are only available to PRO users?
https://mapgenie.io/tarkov

![image](https://github.com/V1P3R-FMG/free-map-genie/assets/100790859/c3047f72-05fb-4cd7-87c7-9e97464b8290)

**Comment by MrFusiion** [comment]
At the moment the extension does not give access to early access maps, and I don't know if I can unlock this PRO feature. Because the server side decides who can or cannot visit the site.

**Comment by MrFusiion** [comment]
> Hello. Does this extension give access to maps in early access that are only available to PRO users? https://mapgenie.io/tarkov
> 
> ![image](https://user-images.githubusercontent.com/100790859/242643719-c3047f72-05fb-4cd7-87c7-9e97464b8290.png)

I wanted to update you on this feature, And I'm happy to say that I have maybe found a solution. But Its all theory at the moment so haven't tested or started on it yet.

**Comment by MrFusiion** [comment]
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/d2748989-4988-4f19-9a37-15ceae273ac5)

I have tested my concept and it works so far. this is the `reserve` map. loaded with a non pro account.
And I will add it as soon as I'm done with the refactoring.

**Comment by LDzik** [comment]
@MrFusiion does it work with other maps tho? If so that would be amazing, I'm asking this question because map tiles for reserve can be accessed, here is an example map tile link: https://tiles.mapgenie.io/games/tarkov/reserve/default-v2/9/255/254.png, for reserve even tho I don't have premium, but I couldn't get access to any map tiles for streets and lighthouse.

**Comment by MrFusiion** [comment]
@LDzik yes I have tested it on streets, reserve and lighthouse and it works.
The tiles for lighthouse are on a different baseurl.

#### Reserve
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/2e933160-9e9f-493f-880d-c0b3161b5d24)

#### Lighthouse
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/4ad24417-fae8-4c91-834d-9d04e84e17a3)

## Preview
#### Reserve
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/98bccf29-18f4-4119-a05c-550c14fe06e6)
#### Lighthouse
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/9a752e8e-70ff-45a5-8003-2e1ac5c7142e)
#### Streets
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/36d396f6-5105-47fb-93e4-915b5b21fa75)

But this feature is not released yet in v1.2.0 of my extension.
Currently still refactoring the code and I'm almost finished, 
so v2.0.0 should have to feature once released.

If you have some knowledge of node.js and you can clone the `refactor` branch and run the current dev build using `yarn start-chrome` or `yarn start-firefox`. But the latest dev build doesn't save you marked progress yet.

**Comment by MrFusiion** [comment]
Your feature request has been added in the latest release [v2.0.0](https://github.com/V1P3R-FMG/free-map-genie/releases/tag/v2.0.0).
