### ISSUE TITLE
Does not work with chrome

### ISSUE THREAD

**Issue by TigodanAC** [V1P3R-FMG/free-map-genie#7]
Yesterday the extension worked, but today it no longer allows you to mark up more than 100 locations (and my already 132 marked up locations are lost). Can anyone check what happened?

**Comment by 00BLOOD** [comment]
It doesn't work on Firefox anymore either.
To be more specific, the extension use to work randomly. Sometimes do, sometimes don't. I keep pressing F5 to update the Elden Ring map genie page, and it doesn't work anymore. Yesterday it was working "fine", but now, map genie doesn't even recognise the extension installed.

**Comment by MrFusiion** [comment]
I tested the latest version of my extension on Firefox and it still works for me.
Maybe if one of you guys can provide an error log?, Can help me find the issue.
And you can always check if your stored map markers are still saved in LocalStorage.
It should be saved under the key `mg:game_<gameid>:user<userid>:v5`.
The game id can be found by typing `game.id` in the browser console, And for the user id `user.id`.
(Make sure to check and remove vulnerable information before sending a screenshot!)

Also wanted to say that I'm currently rewriting the extension using manifest v3, So it could potentially fix the issue.
But I'm not able to tell when its gonna be finished at the moment.

**Comment by 00BLOOD** [comment]
I'm not sure if this is the error log you want, i'm an ignorant on this.

So, let me explain:

As you can see in the image, sometimes when i open the Elden Ring map genie, the page doesn't even load. It keeps loading and never ends.
![03](https://github.com/V1P3R-FMG/free-map-genie/assets/31937724/bbf71ae6-0ac0-4988-90a5-180a12d0daaa)

So, if i hit F5 a few times, the page loads but the addon doesn't work, as you can see here:
![02](https://github.com/V1P3R-FMG/free-map-genie/assets/31937724/5795d30f-c207-4efc-b356-f79285246900)

I learned that if i duplicate the current browser tab (by holding ctrl + drag left click), the addon loads and can fully work.
as you can see in the image, it's working:
![01](https://github.com/V1P3R-FMG/free-map-genie/assets/31937724/0c9843cd-74e8-4b08-90ba-bce478cc237e)

Also, i wouldl ike to mention that my preset keeps being duplicated, and i don't know how:
![04](https://github.com/V1P3R-FMG/free-map-genie/assets/31937724/4b920a9f-3258-41e3-94c2-9c9cf9601d58)

Let me know if you need more screenshots.

**Comment by MrFusiion** [comment]
I'm gonna close this issue in favor of the latest release. A new issue can always be posted if it turns out it still doesn't work as intented.
